#!/usr/bin/env bash
# Configure your domain zone.
check () {
    ptrn="$1"
    d_info=$(dig "$ptrn" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
    d_rc=$(echo "$d_info" | awk '{print $4}')
    d_ip=$(echo "$d_info" | awk '{print $5}')
    echo "The subdomain $2 is a $d_rc record and points to $d_ip"
}

d_name="$1"

if [ $# -eq 1 ]; then
    check "www.$d_name" "www"
    check "lb-01.$d_name" "lb-01"
    check "web-01.$d_name" "web-01"
    check "web-02.$d_name" "web-02"
elif [ $# -eq 2 ]; then
    d="$2.$1"
    check "$d" "$2"
fi
