#!/usr/bin/env bash
# Install nginx web server

# Define variables

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo rm /var/www/html/index.nginx-debian.html
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
