#!/usr/bin/env bash
# 3. Redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo rm /var/www/html/index.nginx-debian.html
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo ufw allow 'Nginx HTTP'
new_string="server_name _;\\n\\n\\tlocation /redirect_me {\\n\\t\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n\\t}"
sudo sed -i "\#location /redirect_me# ! s#server_name _;#$new_string#" /etc/nginx/sites-available/default
sudo service nginx restart
