#!/usr/bin/env bash
# 3. Redirection
config_file="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo rm /var/www/html/index.nginx-debian.html
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo ufw allow 'Nginx HTTP'
# Check if the location block already exists
if ! grep -q "location /redirect_me" "$config_file"; then
    new_string=$(cat <<-EOL
        server_name _;

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
EOL
    )

    # Use awk to replace the "server_name _;" line with the new configuration block
    awk -v new_string="$new_string" '/server_name _;/ { print new_string; next }1' "$config_file" > "$config_file.tmp"

    # Replace the original configuration file with the temporary file
    sudo mv "$config_file.tmp" "$config_file"
fi
sudo service nginx restart
