#!/usr/bin/env bash
# Script to configure nginx to listen on port :80 using sites_*
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restarting nginx to use the new configuration.
sudo service nginx restart
