#!/usr/bin/env bash
# Bash script that handles the trap command with custom functions.

SCRIPT_PID=$$
trap sigquit_sigterm_handler SIGQUIT SIGTERM
trap sigint_handler SIGINT

sigquit_sigterm_handler() {
        echo "I hate the kill command"
        rm "/var/run/myscript.pid"
        exit
}

sigint_handler() {
        echo "Y U no love me?!"
}

echo "$SCRIPT_PID" > /var/run/myscript.pid
while ((1)); do
        echo "To infinity and beyond"
        sleep 2
done

