#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
#+ and displays I am invincible!!! when receiving a SIGTERM signal.

trap sigterm_handler SIGTERM
sigterm_handler() {
	echo "I am invincible!!!"
}
while ((1)); do
	echo "To infinity and beyond"
	sleep 2
done
