#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely.

call()
{
	echo "I am invincible!!!"
}
trap call SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
