#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"
while IFS=: read -r line; do
	vals=$( (cut -d : -f 1,3,6 <<< "$line") )
	echo "$vals"
done < "$file"
