#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

# awk 'S = /^([0-9]{0,3}\.){3}[0-9]{1,3}$/g {if (length($0) != 0) print $S}'  apache-access.log
awk '{for(i=0;i<=NF;i++){if(match($i, /([0-9]{0,3}\.){3}[0-9]{1,3}$/g) && $i == 1){print $i}}}' apache-access.log

