#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes.

i=0
while [[ "$i" != 13 ]]; do
	j=1

	echo "Hour: $i"
	while [[ "$j" != 60 ]]; do
		echo "$j"
		j=$((j+1))
	done
	i=$((i+1))
done 
