#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.old
cp /etc/hosts ~/hosts.a
echo "127.0.0.2		localhost" > ~/hosts.a
echo "8.8.8.8		facebook.com" >> ~/hosts.a
cp -f ~/hosts.a /etc/hosts

