#!/usr/bin/env bash
# A Bash script that displays all active IPv4 IPs on the machine it’s executed on.

file=$(cat "/etc/hosts")
check="$1"

for line in "$file"; do
	echo "$line" | awk '/"$1" ~ "$check"/ {print "$1"}'
done
