#!/usr/bin/env bash
# Stop nginx
sudo service nginx stop
if ! id -u nginx &>/dev/null; then
        sudo useradd -r -s /sbin/nologin nginx
fi
sed -i 's/^user www-data/user nginx/' /etc/nginx/nginx.conf
# 80 -> 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
